logger.info(f"Bot initialized for wallet {self._mask_wallet(self.wallet_address)}")
        logger.info(f"Execution mode: {self.execution_mode}")
        logger.info(f"Trading pairs: {self.trading_pairs}")
        logger.info(f"Fallback mode: {self.safe_fallback_mode}")
        logger.info(f"LLM: Claude Opus 4.6 via OpenRouter")